FROM apache/flink:1.18.1-scala_2.12-java11

ENV FLINK_LIB_DIR=/opt/flink/lib


# Install Python for PyFlink
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python

COPY python-lib/requirements.txt .
RUN pip3 install -r requirements.txt


# COPY connectors
COPY flink/connectors/*.jar ${FLINK_LIB_DIR}/

# COPY custom flink-conf.yaml มาลงใน image
COPY flink/flink-conf.yaml /opt/flink/custom-config/flink-conf.yaml

# Replace default config (เรียบง่ายสุด)
RUN cp /opt/flink/custom-config/flink-conf.yaml /opt/flink/conf/flink-conf.yaml


# Default command
CMD ["bash"]
